name = "Shopify Next.js Starter"
client_id = ""
application_url = "https://example.com"
embedded = true
extension_directories = ["extension/extensions/*"]

[app_proxy]
url = "https://example.com/api/proxy"
subpath = "announcements"
prefix = "apps"

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-10"

  [[webhooks.subscriptions]]
  topics = ["app/uninstalled"]
  uri = "/api/webhooks"

  [[webhooks.subscriptions]]
  compliance_topics = ["customers/data_request", "customers/redact", "shop/redact"]
  uri = "/api/webhooks"

[access.admin]
direct_api_mode = "offline"
embedded_app_direct_api_access = true

[access_scopes]
scopes = "read_products"

[auth]
redirect_urls = []

[pos]
embedded = false
