api_version = "2025-10"
name = "Announcement Banner"
handle = "announcement-banner"
uid = "703ce8c4-c9c1-4ea4-9fe3-4b3e22b2bc67d758e5d2"

[[extensions]]
type = "theme"
name = "Announcement Banner"
handle = "announcement-banner"

  [extensions.capabilities]
  network_access = true
